# Generated by Django 4.2.5 on 2023-11-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_ingredient_remove_drink_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.AddField(
            model_name='drink',
            name='ingredients',
            field=models.TextField(default='list of ingredients'),
            preserve_default=False,
        ),
    ]
